on:
  workflow_dispatch:
    
jobs:
  install-jenkins:
    runs-on: ubuntu-22.04
    name: install jenkins
    permissions:
      id-token: write
    steps:
    - name: Configure Aws Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::222896848746:role/GithubActionsRole
    - name: Checkout
      uses: actions/checkout@v4
    - name: install ansible
      run: |
        sudo apt-add-repository ppa:ansible/ansible
        sudo apt update
        sudo apt install ansible
    - name: install python
      run: |
        sudo apt-get install python3-pip
        pipx inject ansible-core boto3 botocore
    - name: install aws inventory
      run: |
        ansible-galaxy collection install amazon.aws
    - name: get info from ec2 instances
      run: |
        K3SMASTER_IP = $(ansible-inventory -i my_inv.aws_ec2.yml --list | jq -r '.["_meta"].hostvars | to_entries[] | select(.value.tags.Name == "K3s_Master_instance") | .value.private_ip_address')
        echo "k3s master IP is: $K3SMASTER_IP"
        BASTION_HOST_IP = $(ansible-inventory -i my_inv.aws_ec2.yml --list | jq -r '.["_meta"].hostvars | to_entries[] | select(.value.tags.Name == "bastion_host_instance") | .value.private_ip_address')
        echo "k3s master IP is: $BASTION_HOST_IP"