on:
  workflow_dispatch:
  push:
jobs:
  terraform-check:
    runs-on: ubuntu-22.04
    name: Check Terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt
        working-directory: .
 
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Terraform fmt"
          commit_user_name: "github-actions[bot]"
  terraform-plan:
    needs: [terraform-check]
    runs-on: ubuntu-22.04
    name: Run terraform plan command
    permissions:
      id-token: write
    steps:
    - name: Configure Aws Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::222896848746:role/GithubActionsRole
    - name: Checkout
      uses: actions/checkout@v4
    - name: run init
      run: terraform init
    - name: run plan
      run: terraform plan
  terraform-apply:
    needs: [terraform-plan]
    runs-on: ubuntu-22.04
    name: Run terraform apply command
    permissions:
      id-token: write
    steps:
    - name: Configure Aws Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::222896848746:role/GithubActionsRole
    - name: Checkout
      uses: actions/checkout@v4
    - name: init
      run: terraform init -migrate-state
    - name: run apply
      run: terraform apply -auto-approve
    - name: state
      run: terraform state list
    - name: refresh
      run: terraform refresh
    - name: show 
      run: terraform show 
    - name: output ip addr
      run: |
        terraform output master_ip_addr
        echo {TEST} = {terraform output master_ip_addr} >> "$GITHUB_ENV"
        echo "$TEST"