on:
  workflow_dispatch:
  push:

jobs:
  create-role:
    runs-on: ubuntu-latest
    steps:
      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt
        working-directory: .
 
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Terraform fmt"
          commit_user_name: "github-actions[bot]"
      - name: run init
        run: terraform init
      - name: run plan
        run: terraform plan
      - name: run apply
        run: terraform apply -auto-approve
